connectors/llm/interface.py

Intended to fix problems like:
"Based on the search results, I cannot directly answer your question 'hi' as it is too generic. However, I can provide you with information related to the documents provided. <random content>"

Tune prompt to prevent rambling randomness when answer is not known

---

connectors/vector_store/db.py
file_upload_cli.py
resources/agent.py

This will allow us to delete files from agents and their docs in the vector store. This is achieved by adding metadata to our documents.
I updated the `file_upload_cli` so that the repo is passed in and the filename is the whole path. Having the whole path in there prevents things from getting deleted when they shouldn't (i.e. the bonfire has two README.md files). It doesn't _look_ nice in the tables but it gets the job done.
For the vector store:
The metadata is stored in the table `langchain_pg_embedding` in the column `cmetadata`. The metadata itself is a string in a json object format like `{"repo": repo, "agent_id": id, "filename": filename}`. The `id` field is a uuid generated by the vector store automatically and used to delete the documents.
Example file upload:
`python …

Delete documents from agents

---

connectors/config.py
connectors/llm/interface.py
openshift/template.yaml

This patch adds a new config env var `LLM_TEMPERATURE` that is used to configure the temperature for the model. The default is set to `0.7` which is the default for langchain openapi models. Finally we set temperature to `0.3` in the deploy template.

Add temperature as a configurable option

---

connectors/db/file.py
connectors/db/vector.py

Some docs don't have the `# ` header at the very start of the text

Find the first h1 anywhere in doc to determine title

---

connectors/s3/sync.py

If the s3 prefix that an agent is configured to use is completely removed from the agent config, we should delete any files in the vector DB associated with the old prefix. This only applies to a "managed agent" i.e. one that the s3sync is explicitly instructed to configure via s3sync.yaml

Delete files in a managed agent if prefix is no longer configured

---

app.py
connectors/s3/sync.py
docker-compose.yml

Currently if we hit an error while download or embedding a file, the whole sync process aborts
Instead, we will keep a running count of errors encountered during the sync an keep trying to proceed.
At the end, if there were any errors detected while sync'ing an agent, we will log the count and exit with error code 1

Better error handling during doc sync

---

connectors/s3/sync.py

Fixes KeyError that is hit if no objects are found at the given prefix

Handle no objects found at prefix

---

Pipfile
Pipfile.lock
connectors/db/file.py
connectors/db/vector.py

Currently when we split markdown text, we sometimes see single rows in a text chunk. It is probably a combination of a large amount of white space being used in the tables, combined with the fact we split along `\n` as a separator. A row stored by itself in a chunk without the table headers is lacking context about the content.
1. Run the same markdown processing logic on mkdocs .html files and plain .md files
2. Add code to condense large tables so that the header context is preserved within each text chunk when the text is split for embedding. Also, since we are removing a lot of whitespace, we should hopefully be able to capture more rows in a chunk before splitting again.
For example, a table like this:
```
| header1      | header2      | header3      |
| ------------ | ------------ | …
```

Convert markdown tables into condensed format, apply same processing logic to all md content

---

Pipfile
Pipfile.lock
connectors/db/file.py
pytest.ini
tests/test_md_processing.py

Replaces relative links found in markdown files using the document set's citation URL as a base URL. A relative link, e.g.:
```
[Link](../something.md)
```
will be transformed into an absolute link, e.g.:
```
[Link](https://citation.url/path/to/docs/../something.md)
```

Replace relative links

---

connectors/db/file.py
tests/test_md_processing.py

I witnessed some files get truncated after markdown processing. After stepping through each function of `_process_md` it was discovered that the bug was in `_remove_large_md_code_blocks()`
The logic has been tweaked a bit. We now preserve the leading whitespace of the code block when it is removed. This resolves the problem. A unit test was added.

Fix bug when replacing large code block

---

app.py
connectors/s3/sync.py

Running `flask s3sync --force-resync` or `FORCE_RESYNC=true flask s3sync` will result in all files currently stored in the vector DB being marked for deletion.  This effectively wipes out the doc store for each agent configured in the s3 config file. Then all files found in s3 for each agent will be marked for import. This allows for a complete delete/restore for each document set.

Add support for 'force resync' which re-imports files

---

app.py
openshift/s3sync-cronjob.template.yaml

This allows an env var to be set on the cronjob (an isoformat timestamp) that will cause the job to run with force_resync=True as long as `current_time < until_time`

Add FORCE_RESYNC_UNTIL option

---

app.py
connectors/config.py
openshift/backend.template.yaml
openshift/s3sync-cronjob.template.yaml

Enables the HTTP server for `/metrics` to be started if `flask s3sync` is invoked with `S3_SYNC_METRICS_ENABLED`.
This allows prometheus to collect embedding token usage metrics from the s3sync CronJob pods.
Sometimes the sync can completely quickly, and prometheus may not have a chance to scrape metrics before the pod dies. So when the sync is done, the job will sleep for a time determined by `S3_SYNC_METRICS_SLEEP_SECS` to give prometheus more time to scrape from `/metrics`

Export metrics endpoint for s3sync cronjob

---

connectors/db/vector.py

* Do not retry 504's to avoid overloading the service.
* Filter out empty content chunks in an attempt to avoid this error:
```
openai.APIStatusError: Error code: 413 - {'message': 'Input validation error: `inputs` cannot be empty', 'code': 413, 'type': 'Validation'}
```

More s3sync fixes

---

docker-compose.yml
src/tangerine/config.py
src/tangerine/search.py
src/tangerine/sql/fts_tsvector.sql
src/tangerine/sql/hybrid_search.sql
src/tangerine/vector.py

Get hybrid search properly working:
* Use inverse of embedding score in for ranking vector results in hybrid search since `<#>` returns a [negative inner product](https://github.com/pgvector/pgvector?tab=readme-ov-file#querying)
* Improve the SQL query to rank vector score and FTS score and then use RRF to compile a final score for each document chunk (`::numeric` was essential to getting this working, otherwise the calculation was always returning `0.0`)
Other search related improvements:
* Have each SearchProvider rank its results and use RRF to aggregate at the end
* Normalize scores for all SearchProviders results (though we don't really use them now that we use rank and RRF...)
A bit unrelated, but while I was at it ...
* Bring back the title metadata that accidentally disappeared
* …

Get hybrid search working, add search engine score calculations, other fixes

---

src/tangerine/sync/s3.py

We ran migrations to convert 'agent' to 'assistant' but there are still docs in the vector DB with 'agent_id' in the `cmetadata` JSONB column. We'll remove those during a forced resync.

Purge old docs with 'agent_id' metadata

---

src/tangerine/llm.py
src/tangerine/resources/assistant.py
tests/test_chat_api.py

A team noticed that 'search_metadata' was no longer being returned in a non-streaming response. A bug was introduced earlier when we extracted text content.
I refactored this so that llm.ask always returns a generator (for the LLM response text) and a dict of search metadata. It is now up to the API handler to process/format that info however it wants to.

Standard response metadata bugfix, refactor responses

---

src/tangerine/sync/s3.py

If the sync job hits an error fetching s3 bucket info (or any other kind of error) during `compare_files`, the whole process stops. We should continue and record the error like we do for download / embed errors.

Continue sync'ing if error hit during 'compare'

---

src/tangerine/sync/s3.py

Fixes:
```
vector_db.update_cmetadata(**args, commit=False)
TypeError: VectorStoreInterface.update_cmetadata() got an unexpected keyword argument 'filter'
```

Fix kwarg name

---

src/tangerine/resources/assistant.py

We want to record the number of chat sessions initiated by user and client for each assistant. The user will be anonymized so that we do not reveal the real user IDs to prometheus/grafana (unless the name is 'unknown'). This will allow us to see how many unique users we have using each assistant.
assisted-by: cursor v1.2.4 / claude-4-sonnet

Add metric which counts chat sessions

---

src/tangerine/sync/s3.py

The problem is in line 475 where assistant.associate_knowledgebase(knowledgebase.id) is being called with knowledgebase.id (an integer), but the SQLAlchemy relationship is expecting a KnowledgeBase object instance, not just the ID.
Assisted-by: claude v1.0.85

Fix kb associate in s3sync
